<a href="https://colab.research.google.com/github/QuiqueCov/Maestria/blob/main/RegresionLinealMultiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('gym.csv')
x = dataset.iloc[:, :-1].values # variable independiente
y = dataset.iloc[:, -1].values # variable dependiente

In [ ]:
# Variables dummy
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columTransform = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(columTransform.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 56 ... 4 3 30.2]
 [1.0 0.0 46 ... 4 2 32.0]
 [1.0 0.0 32 ... 4 2 24.71]
 ...
 [1.0 0.0 59 ... 5 3 19.5]
 [0.0 1.0 32 ... 3 2 37.74]
 [0.0 1.0 46 ... 2 1 33.38]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

In [ ]:
# Entrenamiendo del modelo de regression multiple
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train) # esto es aprendizaje supervisado

ValueError: could not convert string to float: 'Strength'

In [ ]:
# Prediccion de los resultados del conjunto de pruebas
y_pred = regressor.predict(X_test)
print(y_pred)
#print(X_test)
print(y_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9347068473282546